#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_firmware_skeleton.py

Firmware project skeleton generator for embedded systems.

Supported platforms
  stm32   : STM32 HAL-based project (CMakeLists or Makefile scaffold)
  esp32   : ESP32 ESP-IDF project (CMakeLists + Kconfig scaffold)
  arduino : Arduino sketch project

For each platform the script generates a complete, compilable starting
structure: directory layout, main source file, peripheral driver stubs,
FreeRTOS task template (if requested), and a README with build instructions.

Output is a JSON dict containing every file path and its content as a string.
The user copies these files into their project directory.

Unified dict/JSON output contract.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from textwrap import dedent
from typing import Any, Dict, List, Optional

PLATFORMS  = ("stm32", "esp32", "arduino")
STM32_SERIES = ("F0", "F1", "F4", "G0", "G4", "H7")
PERIPHERALS  = ("uart", "spi", "i2c", "tim", "adc", "dac", "wifi", "ble", "can", "usb")
RTOS_OPTIONS = ("none", "freertos", "zephyr")


# ---------------------------------------------------------------------------
# STM32 HAL skeleton
# ---------------------------------------------------------------------------

def _stm32_main(project: str, series: str, peripherals: List[str], rtos: str) -> str:
    inits = []
    if "uart" in peripherals: inits.append("MX_USART2_UART_Init();")
    if "spi"  in peripherals: inits.append("MX_SPI1_Init();")
    if "i2c"  in peripherals: inits.append("MX_I2C1_Init();")
    if "tim"  in peripherals: inits.append("MX_TIM2_Init();")
    if "adc"  in peripherals: inits.append("MX_ADC1_Init();")
    if "dac"  in peripherals: inits.append("MX_DAC_Init();")
    if "can"  in peripherals: inits.append("MX_CAN1_Init();")
    if "usb"  in peripherals: inits.append("MX_USB_DEVICE_Init();")
    init_block = "\n    ".join(inits) if inits else "/* No peripherals selected */"

    rtos_block = ""
    if rtos == "freertos":
        rtos_block = dedent("""\

            /* FreeRTOS tasks */
            #include "FreeRTOS.h"
            #include "task.h"

            static void app_task(void *arg) {
                (void)arg;
                for (;;) {
                    /* TODO: application logic */
                    vTaskDelay(pdMS_TO_TICKS(100));
                }
            }
            """)

    main_body = dedent(f"""\
        /* {project} — STM32{series} main entry point */
        /* Auto-generated by gen_firmware_skeleton.py  */
        /* Platform: STM32{series} | Peripherals: {', '.join(peripherals) or 'none'} */

        #include "main.h"
        {rtos_block}
        int main(void) {{
            HAL_Init();
            SystemClock_Config();

            /* Peripheral init (generated by CubeMX — replace with your MX_ functions) */
            {init_block}
        """)

    if rtos == "freertos":
        main_body += dedent("""\

                xTaskCreate(app_task, "AppTask", 256, NULL, tskIDLE_PRIORITY + 1, NULL);
                vTaskStartScheduler();
                /* Should never reach here */
                for (;;);
            }
            """)
    else:
        main_body += dedent("""\

                while (1) {
                    /* TODO: main loop */
                    HAL_Delay(10);
                }
            }
            """)

    return main_body


def _stm32_main_h(project: str, series: str) -> str:
    return dedent(f"""\
        /* {project} main.h — STM32{series} */
        #ifndef MAIN_H
        #define MAIN_H

        #include "stm32{series.lower()}xx_hal.h"

        void SystemClock_Config(void);
        void Error_Handler(void);

        #endif /* MAIN_H */
        """)


def _stm32_peripheral_stub(periph: str) -> str:
    periph_up = periph.upper()
    handles = {
        "uart": "extern UART_HandleTypeDef huart2;",
        "spi":  "extern SPI_HandleTypeDef hspi1;",
        "i2c":  "extern I2C_HandleTypeDef hi2c1;",
        "tim":  "extern TIM_HandleTypeDef htim2;",
        "adc":  "extern ADC_HandleTypeDef hadc1;",
        "dac":  "extern DAC_HandleTypeDef hdac;",
        "can":  "extern CAN_HandleTypeDef hcan1;",
    }
    handle_line = handles.get(periph, f"/* {periph_up} handle */" )
    return dedent(f"""\
        /* {periph_up} driver stub — auto-generated */
        #include "main.h"

        {handle_line}

        void {periph}_driver_init(void) {{
            /* TODO: additional {periph_up} configuration beyond CubeMX defaults */
        }}

        void {periph}_driver_process(void) {{
            /* TODO: {periph_up} polling / callback logic */
        }}
        """)


def _stm32_makefile(project: str, series: str) -> str:
    return dedent(f"""\
        # {project} — STM32{series} build scaffold
        # Adapt paths to your STM32CubeF{series[1:]}/G{series[1:]} SDK location

        TARGET   = {project.lower()}
        SERIES   = STM32{series}xx
        CPU      = -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard

        CC       = arm-none-eabi-gcc
        CFLAGS   = $(CPU) -Wall -O2 -g -DUSE_HAL_DRIVER -D$(SERIES)
        LDFLAGS  = $(CPU) -specs=nano.specs -Wl,--gc-sections

        SRC      = $(wildcard Core/Src/*.c)
        INC      = -ICore/Inc -IDrivers/STM32$(SERIES)_HAL_Driver/Inc

        all:
        \t$(CC) $(CFLAGS) $(INC) $(SRC) $(LDFLAGS) -o $(TARGET).elf
        \tarm-none-eabi-objcopy -O binary $(TARGET).elf $(TARGET).bin
        \tarm-none-eabi-size $(TARGET).elf

        flash:
        \tst-flash write $(TARGET).bin 0x8000000

        clean:
        \trm -f $(TARGET).elf $(TARGET).bin
        """)


def _stm32_readme(project: str, series: str, peripherals: List[str], rtos: str) -> str:
    return dedent(f"""\
        # {project}

        Platform : STM32{series}
        Peripherals: {', '.join(peripherals) or 'none selected'}
        RTOS     : {rtos}
        Generated: gen_firmware_skeleton.py

        ## Build

        ### Option A — STM32CubeIDE (recommended)
        1. File → Import → Existing Projects into Workspace
        2. Select this directory
        3. Build Project (Ctrl+B)
        4. Run → Debug (F11)

        ### Option B — arm-none-eabi-gcc + make
        ```bash
        make all
        make flash   # requires st-link
        ```

        ## Project structure
        ```
        {project}/
        ├── Core/
        │   ├── Inc/main.h
        │   └── Src/main.c
        ├── Drivers/          ← add STM32CubeF{series[1:]} HAL drivers here
        ├── Peripherals/      ← generated driver stubs
        ├── Makefile
        └── README.md
        ```

        ## Next steps
        1. Open in STM32CubeMX, configure clock and peripherals, generate MX_ init code.
        2. Copy MX_ generated files into Core/Src and Core/Inc.
        3. Implement TODO sections in each driver stub.
        4. Add gen_crc_frame.py / gen_uart_protocol.py outputs for communication.
        """)


# ---------------------------------------------------------------------------
# ESP32 IDF skeleton
# ---------------------------------------------------------------------------

def _esp32_main(project: str, peripherals: List[str], rtos: str) -> str:
    inits = []
    if "uart" in peripherals:
        inits.append(dedent("""\
            /* UART init */
            uart_config_t uart_cfg = {
                .baud_rate  = 115200,
                .data_bits  = UART_DATA_8_BITS,
                .parity     = UART_PARITY_DISABLE,
                .stop_bits  = UART_STOP_BITS_1,
                .flow_ctrl  = UART_HW_FLOWCTRL_DISABLE,
            };
            uart_driver_install(UART_NUM_1, 1024, 0, 0, NULL, 0);
            uart_param_config(UART_NUM_1, &uart_cfg);"""))
    if "wifi" in peripherals:
        inits.append(dedent("""\
            /* Wi-Fi init */
            esp_netif_init();
            esp_event_loop_create_default();
            esp_netif_create_default_wifi_sta();
            wifi_init_config_t wifi_cfg = WIFI_INIT_CONFIG_DEFAULT();
            esp_wifi_init(&wifi_cfg);"""))
    if "ble" in peripherals:
        inits.append('esp_bt_controller_config_t bt_cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();\n    esp_bt_controller_init(&bt_cfg);')

    init_block = "\n    ".join(inits) if inits else "/* No peripherals configured */"

    task_fn = ""
    if rtos == "freertos":
        task_fn = dedent("""\

            static void app_task(void *arg) {
                for (;;) {
                    /* TODO: application logic */
                    vTaskDelay(pdMS_TO_TICKS(100));
                }
            }
            """)

    task_create = ""
    if rtos == "freertos":
        task_create = '\n    xTaskCreate(app_task, "app", 4096, NULL, 5, NULL);'

    includes = '#include "esp_log.h"\n#include "driver/uart.h"'
    if "wifi" in peripherals:
        includes += '\n#include "esp_wifi.h"\n#include "esp_netif.h"'
    if "ble" in peripherals:
        includes += '\n#include "esp_bt.h"'

    return dedent(f"""\
        /* {project} — ESP32 main entry point */
        /* Auto-generated by gen_firmware_skeleton.py  */
        #include <stdio.h>
        {includes}
        #include "freertos/FreeRTOS.h"
        #include "freertos/task.h"

        static const char *TAG = "{project}";
        {task_fn}
        void app_main(void) {{
            ESP_LOGI(TAG, "{project} starting...");

            {init_block}
            {task_create}
            ESP_LOGI(TAG, "Init complete.");
        }}
        """)


def _esp32_cmakelists(project: str) -> str:
    return dedent(f"""\
        cmake_minimum_required(VERSION 3.16)
        include($ENV{{IDF_PATH}}/tools/cmake/project.cmake)
        project({project.lower()})
        """)


def _esp32_component_cmake(project: str) -> str:
    return dedent(f"""\
        idf_component_register(
            SRCS "main.c"
            INCLUDE_DIRS "."
        )
        """)


def _esp32_kconfig(project: str) -> str:
    return dedent(f"""\
        menu "{project} Configuration"

        config {project.upper()}_LOG_LEVEL
            int "Log verbosity level (0=None ... 5=Verbose)"
            default 3

        config {project.upper()}_UART_BAUD
            int "UART baud rate"
            default 115200

        endmenu
        """)


def _esp32_readme(project: str, peripherals: List[str]) -> str:
    return dedent(f"""\
        # {project}

        Platform : ESP32 (ESP-IDF)
        Peripherals: {', '.join(peripherals) or 'none selected'}
        Generated: gen_firmware_skeleton.py

        ## Prerequisites
        - ESP-IDF v5.x installed and `idf.py` on PATH
        - `IDF_PATH` environment variable set

        ## Build and flash
        ```bash
        idf.py set-target esp32
        idf.py menuconfig      # optional: tweak Kconfig options
        idf.py build
        idf.py -p /dev/ttyUSB0 flash monitor
        ```

        ## Project structure
        ```
        {project}/
        ├── main/
        │   ├── CMakeLists.txt
        │   ├── Kconfig.projbuild
        │   └── main.c
        ├── CMakeLists.txt
        └── README.md
        ```

        ## Next steps
        1. Implement TODO sections in main.c.
        2. Add components for custom drivers under components/.
        3. Integrate gen_uart_protocol.py generated files for communication.
        """)


# ---------------------------------------------------------------------------
# Arduino skeleton
# ---------------------------------------------------------------------------

def _arduino_sketch(project: str, peripherals: List[str]) -> str:
    setup_lines = ["Serial.begin(115200);", 'Serial.println("' + project + ' starting...");']
    if "spi" in peripherals:  setup_lines.append("SPI.begin();")
    if "i2c" in peripherals:  setup_lines.append("Wire.begin();")

    loop_lines = ["/* TODO: main loop */", "delay(10);"]

    setup_block = "\n    ".join(setup_lines)
    loop_block  = "\n    ".join(loop_lines)

    return dedent(f"""\
        /*
         * {project} — Arduino sketch
         * Auto-generated by gen_firmware_skeleton.py
         * Platform: Arduino (AVR/ESP32/STM32 via Arduino core)
         */
        {"#include <SPI.h>" if "spi" in peripherals else ""}
        {"#include <Wire.h>" if "i2c" in peripherals else ""}

        void setup() {{
            {setup_block}
        }}

        void loop() {{
            {loop_block}
        }}
        """).strip() + "\n"


def _arduino_readme(project: str) -> str:
    return dedent(f"""\
        # {project}

        Platform : Arduino
        Generated: gen_firmware_skeleton.py

        ## Build
        1. Open {project}.ino in the Arduino IDE (≥ 2.0)
        2. Select your board (Tools → Board)
        3. Upload (Ctrl+U)

        ## Next steps
        - Avoid `delay()` in production; use `millis()` for non-blocking timing.
        - For more complex logic, migrate to STM32CubeIDE or ESP-IDF.
        """)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

@dataclass
class SkeletonOutput:
    success:         bool
    inputs:          Dict[str, Any]
    results:         Dict[str, Any]
    warnings:        List[str]
    recommendations: List[str]
    next_actions:    List[str]
    error:           Optional[Dict[str, str]] = None


def gen_firmware_skeleton(
    platform:     str,
    project_name: str           = "MyProject",
    series:       str           = "G4",
    peripherals:  List[str]     = None,
    rtos:         str           = "none",
) -> Dict[str, Any]:
    """
    Generate a firmware project skeleton.

    Parameters
    ----------
    platform     : "stm32" | "esp32" | "arduino"
    project_name : Project/module name (used in file names and guards)
    series       : STM32 series (F0/F1/F4/G0/G4/H7), ignored for other platforms
    peripherals  : List of peripheral names to include stubs for
    rtos         : "none" | "freertos" | "zephyr"
    """
    peripherals = [p.lower().strip() for p in (peripherals or [])]
    inputs: Dict[str, Any] = {
        "platform": platform, "project_name": project_name,
        "series": series, "peripherals": peripherals, "rtos": rtos,
    }

    try:
        plat = platform.lower().strip()
        if plat not in PLATFORMS:
            raise ValueError(f"Platform must be one of {PLATFORMS}; got '{platform}'")

        rtos_key = rtos.lower().strip()
        if rtos_key not in RTOS_OPTIONS:
            raise ValueError(f"RTOS must be one of {RTOS_OPTIONS}; got '{rtos}'")

        unknown_periph = [p for p in peripherals if p not in PERIPHERALS]
        if unknown_periph:
            raise ValueError(
                f"Unknown peripherals: {unknown_periph}. "
                f"Supported: {list(PERIPHERALS)}"
            )

        proj = project_name.strip().replace(" ", "_")
        files: Dict[str, str] = {}
        warnings:  List[str] = []
        recs:      List[str] = []

        if plat == "stm32":
            ser = series.upper().strip()
            if ser not in STM32_SERIES:
                raise ValueError(f"STM32 series must be one of {STM32_SERIES}; got '{series}'")

            files[f"{proj}/Core/Src/main.c"]      = _stm32_main(proj, ser, peripherals, rtos_key)
            files[f"{proj}/Core/Inc/main.h"]      = _stm32_main_h(proj, ser)
            files[f"{proj}/Makefile"]             = _stm32_makefile(proj, ser)
            files[f"{proj}/README.md"]            = _stm32_readme(proj, ser, peripherals, rtos_key)
            for p in peripherals:
                if p in ("uart","spi","i2c","tim","adc","dac","can"):
                    files[f"{proj}/Peripherals/{p}_driver.c"] = _stm32_peripheral_stub(p)

            if rtos_key == "freertos":
                recs.append(
                    "Add FreeRTOS source files from STM32CubeMX or copy from "
                    "github.com/FreeRTOS/FreeRTOS-Kernel into Middlewares/FreeRTOS/."
                )
            if "wifi" in peripherals or "ble" in peripherals:
                warnings.append(
                    "STM32 does not have built-in Wi-Fi/BLE. "
                    "Use an external module (ESP-AT, ESP32 co-processor, or Nordic nRF) "
                    "and communicate via UART or SPI."
                )

        elif plat == "esp32":
            files[f"{proj}/main/main.c"]                     = _esp32_main(proj, peripherals, rtos_key)
            files[f"{proj}/main/CMakeLists.txt"]             = _esp32_component_cmake(proj)
            files[f"{proj}/main/Kconfig.projbuild"]          = _esp32_kconfig(proj)
            files[f"{proj}/CMakeLists.txt"]                  = _esp32_cmakelists(proj)
            files[f"{proj}/README.md"]                       = _esp32_readme(proj, peripherals)

            if "can" in peripherals:
                warnings.append(
                    "ESP32 does not have a built-in CAN controller. "
                    "Use TWAI (Two-Wire Automotive Interface) with an external TJA1050 transceiver."
                )
            if "dac" in peripherals:
                recs.append(
                    "ESP32 has a built-in 8-bit DAC on GPIO25/GPIO26. "
                    "Use dac_output_enable() / dac_output_voltage() from driver/dac.h."
                )

        else:  # arduino
            files[f"{proj}/{proj}.ino"] = _arduino_sketch(proj, peripherals)
            files[f"{proj}/README.md"]  = _arduino_readme(proj)

            if rtos_key != "none":
                warnings.append(
                    "RTOS on Arduino is non-standard. "
                    "Consider migrating to ESP-IDF (ESP32) or STM32CubeIDE (STM32) for RTOS support."
                )

        # Common recommendations
        recs.append(
            "Integrate gen_uart_protocol.py output for custom serial communication "
            "by adding the generated .h/.c files to the project."
        )
        recs.append(
            "Add gen_crc_frame.py generated CRC function to a shared crc_utils.c/h."
        )
        recs.append(
            "Set up version control (git init) immediately and commit this skeleton "
            "as the initial commit before adding application logic."
        )

        dir_listing = sorted(files.keys())

        return asdict(SkeletonOutput(
            success=True, inputs=inputs,
            results={
                "files": files,
                "file_count": len(files),
                "directory_listing": dir_listing,
                "instructions": (
                    f"Create the directory '{proj}/' and write each file listed in "
                    "'files' at its given path. Then follow the README.md build steps."
                ),
            },
            warnings=warnings, recommendations=recs,
            next_actions=["gen_crc_frame", "gen_uart_protocol"],
        ))

    except Exception as exc:
        return asdict(SkeletonOutput(
            success=False, inputs=inputs, results={},
            warnings=[], recommendations=[], next_actions=[],
            error={"code": exc.__class__.__name__.upper(), "message": str(exc)},
        ))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(
        description="Firmware project skeleton generator",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--platform",   required=True, choices=PLATFORMS)
    p.add_argument("--project",    default="MyProject", dest="project_name")
    p.add_argument("--series",     default="G4",
                   help="STM32 series: F0/F1/F4/G0/G4/H7")
    p.add_argument("--peripherals", default="",
                   help="Comma-separated: uart,spi,i2c,tim,adc,dac,wifi,ble,can,usb")
    p.add_argument("--rtos",       default="none", choices=RTOS_OPTIONS)
    args = p.parse_args()

    periph_list = [x.strip() for x in args.peripherals.split(",") if x.strip()]
    result = gen_firmware_skeleton(
        platform=args.platform, project_name=args.project_name,
        series=args.series, peripherals=periph_list, rtos=args.rtos,
    )
    # Print without file contents to keep output readable in CLI
    out = dict(result)
    if "results" in out and "files" in out["results"]:
        out["results"] = dict(out["results"])
        out["results"]["files"] = {
            k: f"<{len(v)} chars>" for k, v in out["results"]["files"].items()
        }
    print(json.dumps(out, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
