#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_uart_protocol.py

UART custom protocol frame definition and C firmware code generator
for embedded communication workflows.

Given a protocol name, baud rate, frame header, CRC type, and a list of
command definitions, this script generates:

- Validated frame structure description (field widths, byte budget)
- Complete C header file (.h): enums, frame struct, function prototypes
- Complete C source file (.c): pack / unpack / send / receive skeleton
- Python reference implementation for host-side testing
- Unified dict/JSON output contract

Frame format (fixed):
  [HEADER_0][HEADER_1][LEN][CMD][PAYLOAD...][CRC]

LEN  = number of PAYLOAD bytes (not counting CMD or CRC)
CRC  = computed over [LEN][CMD][PAYLOAD]
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from textwrap import dedent
from typing import Any, Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Command descriptor
# ---------------------------------------------------------------------------

@dataclass
class Command:
    name:     str    # e.g. "READ_SENSOR"
    code:     int    # e.g. 0x01
    direction: str   # "host_to_device" | "device_to_host" | "bidirectional"
    payload_len: int # fixed payload byte count, -1 = variable
    description: str


def _parse_commands(raw: str) -> List[Command]:
    """
    Parse command string like:
      "READ_SENSOR:0x01,SET_CONFIG:0x02,ACK:0x10"
    or extended JSON-like:
      "READ_SENSOR:0x01:4:host_to_device,ACK:0x10:0:device_to_host"
    """
    cmds: List[Command] = []
    for part in raw.split(","):
        part = part.strip()
        if not part:
            continue
        fields = part.split(":")
        name  = fields[0].strip().upper().replace(" ", "_")
        code  = int(fields[1].strip(), 16) if len(fields) > 1 else 0x00
        plen  = int(fields[2].strip()) if len(fields) > 2 else -1
        direc = fields[3].strip() if len(fields) > 3 else "bidirectional"
        desc  = fields[4].strip() if len(fields) > 4 else ""
        cmds.append(Command(name=name, code=code, direction=direc,
                            payload_len=plen, description=desc))
    return cmds


# ---------------------------------------------------------------------------
# C code generation
# ---------------------------------------------------------------------------

_CRC_TYPE_MAP = {
    "CRC8":         ("uint8_t",  1, "calc_crc8"),
    "CRC8_MAXIM":   ("uint8_t",  1, "calc_crc8_maxim"),
    "CRC16_MODBUS": ("uint16_t", 2, "calc_crc16_modbus"),
    "CRC16_CCITT":  ("uint16_t", 2, "calc_crc16_ccitt"),
    "CRC32":        ("uint32_t", 4, "calc_crc32"),
}


def _gen_header(
    proto_name: str,
    header_bytes: bytes,
    baud: int,
    commands: List[Command],
    crc_type: str,
    max_payload: int,
) -> str:
    guard  = re.sub(r"\W", "_", proto_name).upper() + "_H"
    ctype, crc_size, crc_fn = _CRC_TYPE_MAP.get(crc_type, ("uint8_t", 1, "calc_crc8"))
    header_hex = ", ".join(f"0x{b:02X}" for b in header_bytes)
    cmd_enum   = "\n".join(
        f"    CMD_{c.name:<24} = 0x{c.code:02X}U,  /* {c.description or c.direction} */"
        for c in commands
    )
    max_frame = 2 + 1 + 1 + max_payload + crc_size   # header + len + cmd + payload + crc

    return dedent(f"""\
        /* Auto-generated by gen_uart_protocol.py */
        #ifndef {guard}
        #define {guard}

        #include <stdint.h>
        #include <stddef.h>
        #include <stdbool.h>

        /* ---- Protocol constants ---- */
        #define {proto_name.upper()}_BAUD_RATE     {baud}U
        #define {proto_name.upper()}_HEADER_0      {f"0x{header_bytes[0]:02X}U" if header_bytes else "0xAAU"}
        #define {proto_name.upper()}_HEADER_1      {f"0x{header_bytes[1]:02X}U" if len(header_bytes) > 1 else "0x55U"}
        #define {proto_name.upper()}_MAX_PAYLOAD   {max_payload}U
        #define {proto_name.upper()}_MAX_FRAME     {max_frame}U
        #define {proto_name.upper()}_CRC_SIZE      {crc_size}U

        /* ---- Command codes ---- */
        typedef enum {{
        {cmd_enum}
        }} {proto_name}_cmd_t;

        /* ---- Frame state machine ---- */
        typedef enum {{
            FRAME_STATE_IDLE,
            FRAME_STATE_HEADER1,
            FRAME_STATE_LEN,
            FRAME_STATE_CMD,
            FRAME_STATE_PAYLOAD,
            FRAME_STATE_CRC,
        }} {proto_name}_rx_state_t;

        /* ---- Frame context ---- */
        typedef struct {{
            {proto_name}_rx_state_t state;
            uint8_t  len;
            uint8_t  cmd;
            uint8_t  payload[{proto_name.upper()}_MAX_PAYLOAD];
            uint16_t payload_idx;
            {ctype}  crc_received;
            uint8_t  crc_byte_idx;
        }} {proto_name}_rx_ctx_t;

        /* ---- Public API ---- */
        /* Pack a frame into buf. Returns frame length in bytes. */
        uint16_t {proto_name}_pack(uint8_t cmd, const uint8_t *payload, uint8_t plen,
                                    uint8_t *buf, uint16_t buf_size);

        /* Feed one received byte into the state machine.
           Returns true when a complete, CRC-valid frame has been received. */
        bool {proto_name}_feed_byte(uint8_t byte, {proto_name}_rx_ctx_t *ctx);

        /* Reset receiver context (call after error or frame handled). */
        void {proto_name}_reset_ctx({proto_name}_rx_ctx_t *ctx);

        /* CRC function — implement using gen_crc_frame.py output */
        {ctype} {crc_fn}(const uint8_t *data, size_t len);

        #endif /* {guard} */
        """)


def _gen_source(
    proto_name: str,
    header_bytes: bytes,
    commands: List[Command],
    crc_type: str,
    max_payload: int,
) -> str:
    ctype, crc_size, crc_fn = _CRC_TYPE_MAP.get(crc_type, ("uint8_t", 1, "calc_crc8"))
    pname_up = proto_name.upper()

    crc_pack = ""
    if crc_size == 1:
        crc_pack = dedent("""\
            buf[pos++] = (uint8_t)crc;
            """)
    elif crc_size == 2:
        crc_pack = dedent("""\
            buf[pos++] = (uint8_t)(crc >> 8);   /* big-endian */
            buf[pos++] = (uint8_t)(crc & 0xFF);
            """)
    else:
        crc_pack = dedent("""\
            buf[pos++] = (uint8_t)(crc >> 24);
            buf[pos++] = (uint8_t)(crc >> 16);
            buf[pos++] = (uint8_t)(crc >> 8);
            buf[pos++] = (uint8_t)(crc & 0xFF);
            """)

    crc_accum = ""
    if crc_size == 1:
        crc_accum = "ctx->crc_received = byte;"
    elif crc_size == 2:
        crc_accum = dedent("""\
            if (ctx->crc_byte_idx == 0) ctx->crc_received  = (uint16_t)byte << 8;
            else                        ctx->crc_received |= byte;
            """).strip()
    else:
        crc_accum = dedent("""\
            ctx->crc_received = (ctx->crc_received << 8) | byte;
            """).strip()

    return dedent(f"""\
        /* Auto-generated by gen_uart_protocol.py */
        #include "{proto_name}.h"
        #include <string.h>

        /* ---- Frame packer ---- */
        uint16_t {proto_name}_pack(uint8_t cmd, const uint8_t *payload, uint8_t plen,
                                    uint8_t *buf, uint16_t buf_size)
        {{
            if (buf_size < (uint16_t)(2U + 1U + 1U + plen + {pname_up}_CRC_SIZE))
                return 0U;

            uint16_t pos = 0;
            buf[pos++] = {pname_up}_HEADER_0;
            buf[pos++] = {pname_up}_HEADER_1;
            buf[pos++] = plen;                      /* LEN = payload bytes only */
            buf[pos++] = cmd;

            if (payload && plen)
                memcpy(&buf[pos], payload, plen);
            pos += plen;

            /* CRC covers [LEN][CMD][PAYLOAD] */
            {ctype} crc = {crc_fn}(&buf[2], (size_t)(2U + plen));
            {crc_pack}
            return pos;
        }}

        /* ---- Receiver context reset ---- */
        void {proto_name}_reset_ctx({proto_name}_rx_ctx_t *ctx)
        {{
            memset(ctx, 0, sizeof(*ctx));
            ctx->state = FRAME_STATE_IDLE;
        }}

        /* ---- Byte-feed state machine ---- */
        bool {proto_name}_feed_byte(uint8_t byte, {proto_name}_rx_ctx_t *ctx)
        {{
            switch (ctx->state) {{

                case FRAME_STATE_IDLE:
                    if (byte == {pname_up}_HEADER_0)
                        ctx->state = FRAME_STATE_HEADER1;
                    break;

                case FRAME_STATE_HEADER1:
                    ctx->state = (byte == {pname_up}_HEADER_1)
                                 ? FRAME_STATE_LEN : FRAME_STATE_IDLE;
                    break;

                case FRAME_STATE_LEN:
                    if (byte > {pname_up}_MAX_PAYLOAD) {{
                        {proto_name}_reset_ctx(ctx);   /* oversized frame */
                        break;
                    }}
                    ctx->len         = byte;
                    ctx->payload_idx = 0;
                    ctx->state       = FRAME_STATE_CMD;
                    break;

                case FRAME_STATE_CMD:
                    ctx->cmd   = byte;
                    ctx->state = (ctx->len > 0) ? FRAME_STATE_PAYLOAD : FRAME_STATE_CRC;
                    ctx->crc_byte_idx = 0;
                    break;

                case FRAME_STATE_PAYLOAD:
                    ctx->payload[ctx->payload_idx++] = byte;
                    if (ctx->payload_idx >= ctx->len) {{
                        ctx->state        = FRAME_STATE_CRC;
                        ctx->crc_byte_idx = 0;
                    }}
                    break;

                case FRAME_STATE_CRC: {{
                    {crc_accum}
                    ctx->crc_byte_idx++;
                    if (ctx->crc_byte_idx >= {pname_up}_CRC_SIZE) {{
                        /* Recompute CRC over [LEN][CMD][PAYLOAD] */
                        uint8_t tmp[2 + {pname_up}_MAX_PAYLOAD];
                        tmp[0] = ctx->len;
                        tmp[1] = ctx->cmd;
                        if (ctx->len) memcpy(&tmp[2], ctx->payload, ctx->len);
                        {ctype} expected = {crc_fn}(tmp, (size_t)(2U + ctx->len));
                        bool valid = (expected == ctx->crc_received);
                        {proto_name}_reset_ctx(ctx);
                        return valid;
                    }}
                    break;
                }}

                default:
                    {proto_name}_reset_ctx(ctx);
                    break;
            }}
            return false;
        }}
        """)


def _gen_python_ref(
    proto_name: str,
    header_bytes: bytes,
    baud: int,
    commands: List[Command],
    crc_type: str,
) -> str:
    hdr0 = header_bytes[0] if header_bytes else 0xAA
    hdr1 = header_bytes[1] if len(header_bytes) > 1 else 0x55

    cmd_consts = "\n".join(
        f"    {c.name:<24} = 0x{c.code:02X}" for c in commands
    )

    return dedent(f"""\
        \"\"\"
        {proto_name} — Python reference implementation (host side)
        Auto-generated by gen_uart_protocol.py
        \"\"\"
        import struct
        import serial
        from gen_crc_frame import gen_crc_frame, ALGOS, _compute_crc, _parse_hex

        BAUD   = {baud}
        HDR_0  = 0x{hdr0:02X}
        HDR_1  = 0x{hdr1:02X}
        CRC_ALGO = "{crc_type}"

        class Cmd:
        {cmd_consts}


        def _crc(data: bytes) -> bytes:
            algo = ALGOS[CRC_ALGO]
            val  = _compute_crc(data, algo)
            return val.to_bytes(algo.width // 8, "big")


        def pack(cmd: int, payload: bytes = b"") -> bytes:
            \"\"\"Build a protocol frame.\"\"\"
            body = bytes([len(payload), cmd]) + payload
            return bytes([HDR_0, HDR_1]) + body + _crc(body)


        def send(port: serial.Serial, cmd: int, payload: bytes = b"") -> None:
            frame = pack(cmd, payload)
            port.write(frame)


        def receive(port: serial.Serial, timeout: float = 1.0) -> dict | None:
            \"\"\"
            Blocking receive.  Returns dict(cmd, payload) or None on timeout/error.
            \"\"\"
            port.timeout = timeout
            algo    = ALGOS[CRC_ALGO]
            crc_len = algo.width // 8
            buf     = bytearray()
            state   = "IDLE"
            plen    = 0

            while True:
                b = port.read(1)
                if not b:
                    return None
                byte = b[0]

                if state == "IDLE":
                    if byte == HDR_0: state = "HDR1"
                elif state == "HDR1":
                    state = "LEN" if byte == HDR_1 else "IDLE"
                elif state == "LEN":
                    plen  = byte
                    buf   = bytearray([plen])
                    state = "CMD"
                elif state == "CMD":
                    cmd_byte = byte
                    buf.append(byte)
                    state = "PAYLOAD" if plen else "CRC"
                elif state == "PAYLOAD":
                    buf.append(byte)
                    if len(buf) >= plen + 2:   # len byte + cmd + payload
                        state = "CRC"
                elif state == "CRC":
                    buf.append(byte)
                    if len(buf) >= plen + 2 + crc_len:
                        payload_data = bytes(buf[2:-crc_len])
                        rx_crc       = int.from_bytes(buf[-crc_len:], "big")
                        expected     = _compute_crc(bytes(buf[:-crc_len]), algo)
                        if rx_crc == expected:
                            return {{"cmd": cmd_byte, "payload": payload_data}}
                        return None   # CRC mismatch


        if __name__ == "__main__":
            import sys
            port = serial.Serial(sys.argv[1] if len(sys.argv) > 1 else "/dev/ttyUSB0",
                                 BAUD, timeout=1)
            print("Sending READ_SENSOR command...")
            send(port, Cmd.{"READ_SENSOR" if any(c.name == "READ_SENSOR" for c in commands) else commands[0].name if commands else "CMD_0x01"})
            resp = receive(port)
            print("Response:", resp)
        """)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

@dataclass
class UARTProtoOutput:
    success:         bool
    inputs:          Dict[str, Any]
    results:         Dict[str, Any]
    warnings:        List[str]
    recommendations: List[str]
    next_actions:    List[str]
    error:           Optional[Dict[str, str]] = None


def gen_uart_protocol(
    name:              str,
    baud:              int               = 115200,
    frame_header_hex:  str               = "AA 55",
    crc_type:          str               = "CRC8",
    commands_str:      str               = "READ:0x01,WRITE:0x02,ACK:0x10",
    max_payload_bytes: int               = 64,
) -> Dict[str, Any]:
    """
    Generate a UART custom protocol definition with C and Python code.

    Parameters
    ----------
    name              : Protocol/module name, e.g. "SensorProtocol"
    baud              : UART baud rate
    frame_header_hex  : Sync header bytes, e.g. "AA 55"
    crc_type          : CRC algorithm (CRC8 / CRC16_MODBUS / CRC16_CCITT / CRC32)
    commands_str      : Comma-separated commands: "NAME:0xCODE[:payload_len[:dir]]"
    max_payload_bytes : Maximum payload size per frame
    """
    inputs: Dict[str, Any] = {
        "name": name, "baud": baud,
        "frame_header_hex": frame_header_hex,
        "crc_type": crc_type, "commands_str": commands_str,
        "max_payload_bytes": max_payload_bytes,
    }

    try:
        from gen_crc_frame import ALGOS
    except ImportError:
        ALGOS_KEYS = ["CRC8", "CRC8_MAXIM", "CRC16_MODBUS", "CRC16_CCITT", "CRC16_IBM", "CRC32"]
        if crc_type.upper() not in ALGOS_KEYS:
            pass  # will catch below

    try:
        crc_key = crc_type.upper().strip()
        if crc_key not in _CRC_TYPE_MAP:
            raise ValueError(
                f"Unsupported CRC type '{crc_type}'. "
                f"Supported: {', '.join(_CRC_TYPE_MAP)}"
            )
        if max_payload_bytes < 1 or max_payload_bytes > 512:
            raise ValueError("max_payload_bytes must be between 1 and 512.")

        proto_name   = re.sub(r"\W", "_", name.strip())
        header_bytes = bytes(int(t, 16) for t in frame_header_hex.split() if t)
        if len(header_bytes) < 2:
            raise ValueError("frame_header_hex must contain at least 2 bytes.")

        commands = _parse_commands(commands_str)
        if not commands:
            raise ValueError("At least one command must be specified.")

        # Check for duplicate command codes
        codes_seen: Dict[int, str] = {}
        for c in commands:
            if c.code in codes_seen:
                raise ValueError(
                    f"Duplicate command code 0x{c.code:02X} "
                    f"({codes_seen[c.code]} and {c.name})."
                )
            codes_seen[c.code] = c.name

        crc_size = _CRC_TYPE_MAP[crc_key][1]
        max_frame = 2 + 1 + 1 + max_payload_bytes + crc_size

        h_code  = _gen_header(proto_name, header_bytes, baud, commands, crc_key, max_payload_bytes)
        c_code  = _gen_source(proto_name, header_bytes, commands, crc_key, max_payload_bytes)
        py_code = _gen_python_ref(proto_name, header_bytes, baud, commands, crc_key)

        frame_structure = {
            "byte_0":      f"0x{header_bytes[0]:02X} (header sync 0)",
            "byte_1":      f"0x{header_bytes[1]:02X} (header sync 1)",
            "byte_2":      "LEN  — payload byte count (0–" + str(max_payload_bytes) + ")",
            "byte_3":      "CMD  — command code",
            "byte_4_to_N": "PAYLOAD (0–" + str(max_payload_bytes) + " bytes)",
            "last_bytes":  f"CRC  ({crc_size} byte{'s' if crc_size > 1 else ''}, {crc_key})",
            "crc_coverage": "[LEN][CMD][PAYLOAD]",
            "max_frame_bytes": max_frame,
        }

        cmd_table = [
            {"name": c.name, "code": f"0x{c.code:02X}",
             "direction": c.direction, "payload_len": c.payload_len,
             "description": c.description}
            for c in commands
        ]

        warnings: List[str] = []
        if baud > 921600:
            warnings.append(
                f"Baud rate {baud} is very high; verify UART clock accuracy "
                "and cable/line capacitance."
            )
        if max_payload_bytes > 128:
            warnings.append(
                f"MAX_PAYLOAD = {max_payload_bytes} bytes; ensure the receiving MCU "
                "has sufficient RAM for the frame buffer."
            )
        if crc_key == "CRC8" and max_payload_bytes > 16:
            warnings.append(
                "CRC8 with large payloads has limited error-detection capability. "
                "Consider CRC16_MODBUS or CRC32 for payloads > 16 bytes."
            )

        recs: List[str] = [
            "Copy gen_crc_frame.py output for the CRC function into a "
            "separate crc_utils.c/h file and link it with the generated source.",
            "Use DMA + UART IDLE-line interrupt (STM32 HAL_UARTEx_ReceiveToIdle_DMA) "
            "for efficient non-blocking reception on STM32.",
            "On ESP32, use uart_driver_install() with a ring buffer; "
            "process frames in a dedicated FreeRTOS task.",
            "Add a sequence number or timestamp field to the payload if out-of-order "
            "or dropped-packet detection is required.",
        ]

        return asdict(UARTProtoOutput(
            success=True, inputs=inputs,
            results={
                "frame_structure":   frame_structure,
                "command_table":     cmd_table,
                "c_header":          h_code,
                "c_source":          c_code,
                "python_reference":  py_code,
                "files_to_create":   [
                    f"{proto_name}.h  (copy c_header)",
                    f"{proto_name}.c  (copy c_source, implement crc function)",
                    f"{proto_name}_host.py  (copy python_reference)",
                ],
            },
            warnings=warnings, recommendations=recs,
            next_actions=["gen_firmware_skeleton", "gen_crc_frame"],
        ))

    except Exception as exc:
        return asdict(UARTProtoOutput(
            success=False, inputs=inputs, results={},
            warnings=[], recommendations=[], next_actions=[],
            error={"code": exc.__class__.__name__.upper(), "message": str(exc)},
        ))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(
        description="UART protocol frame definition and C/Python code generator",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--name",        required=True,  help="Protocol/module name")
    p.add_argument("--baud",        type=int, default=115200)
    p.add_argument("--frame-header", default="AA 55", dest="frame_header_hex")
    p.add_argument("--crc",          default="CRC8", dest="crc_type",
                   choices=list(_CRC_TYPE_MAP))
    p.add_argument("--commands",    required=True, dest="commands_str",
                   help="CMD1:0xCODE,CMD2:0xCODE  or  CMD:0xCODE:payload_len:direction")
    p.add_argument("--max-payload", type=int, default=64, dest="max_payload_bytes")
    args = p.parse_args()

    result = gen_uart_protocol(
        name=args.name, baud=args.baud,
        frame_header_hex=args.frame_header_hex,
        crc_type=args.crc_type, commands_str=args.commands_str,
        max_payload_bytes=args.max_payload_bytes,
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
